config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "bands", to: "bands#index", as: "bands"
  post "bands", to: "bands#create"
  get "bands/new", to: "bands#new", as: "new_band"
  get "bands/:id", to: "bands#show", as: "band"
  delete "bands/:id", to: "bands#destroy"
  patch "bands/:id", to: "bands#update"
  get "bands/:id/edit", to: "bands#edit", as: "edit_band"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :genre
  has_many :albums

  validates :name, presence: true
  validates :description, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :bands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  before_action :set_band, only: [:show, :destroy, :edit, :update]
  before_action :set_genres, only: [:new, :edit]
  
  
  def index
    @bands = Band.all.includes(:genre)
  end

  def show
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_path
    else
      set_genres
      render "new"
    end
  end

  def destroy
    @band.destroy 
    redirect_to bands_path
  end
  
  def edit
  end

  def update
    if @band.update(band_params)
      redirect_to bands_path
    else
      set_genres
      render "edit"
    end
  end
  
  private
  
  def band_params
    params.require(:band).permit(:name, :genre_id, :description)
  end

  def set_genres
    @genres = Genre.all
  end

  def set_band
    begin
      @band = Band.find(params[:id])
    rescue
      render "not_found"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bands/_form.html.erb
<%=form_with model: @band, local: true do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :genre %>
      <%= form.select :genre_id, @genres.map {|g| [g.name, g.id]} %>
    </div>
    
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
    
    <div class="field">
      <%= form.submit %>
    </div>
    <%end %>

app/views/bands/edit.html.erb
<h1> Update <%=@band.name%></h1>
<%= render "form" %>

<% if @band.errors.any? %>
<p>There's something wrong</p>
<% @band.errors.full_messages.each do |message| %>
  <ul>
    <li><%=message%></li>
  </ul>
  <%end%>
<%end%>

app/views/bands/index.html.erb
<main id="bands-index">
  <h1>All the bands!</h1>
  <section class="card-deck">
    <%@bands.each do |band| %>
      <div class="card">
        <h5><%= band.name%></h5>
        <p><%= band.description%></p>
        <%=link_to "See More", band_path(band.id)%>
      </div> 
    <%end%>
  </section>
</main>

app/views/bands/new.html.erb
<h1> Create a new band </h1>
<%= render "form" %>

app/views/bands/not_found.html.erb
<p>Seems like the band you were looking for doesn't exist</p>

app/views/bands/show.html.erb
<h1><%=@band.name%></h1>
<h2><%=@band.genre.name%></h2>
<p><%=@band.description%></p>
<%= link_to "Back", bands_path%>
<div class="button-container">
  <%= button_to "Delete Band", {action: "destroy", id: @band.id}, {method: :delete, class: "btn danger", data: {confirm: "Are you sure?"}} %>
  <%= button_to "Edit Band", {action: "edit", id: @band.id}, {method: :get, class: "btn warning"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "/shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Discogs</h1>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to "Home", root_path %>
  <%= link_to "Create a Band", new_band_path %>
  <%= link_to "See all Bands", bands_path %>
</nav>